import type { Category } from "@/lib/types/finance"

const seededAt = "2026-01-01T00:00:00.000Z"

export const defaultCategories: Category[] = [
  {
    id: "cat-food",
    name: "Makanan & Minuman",
    icon: "Utensils",
    emoji: "🍽️",
    color: "#FF6B47",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-transport",
    name: "Transportasi",
    icon: "Car",
    emoji: "🚗",
    color: "#06B6D4",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-shopping",
    name: "Belanja",
    icon: "ShoppingBag",
    emoji: "🛍️",
    color: "#8B5CF6",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-bills",
    name: "Tagihan",
    icon: "Lightbulb",
    emoji: "💡",
    color: "#F59E0B",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-entertainment",
    name: "Hiburan",
    icon: "Clapperboard",
    emoji: "🎬",
    color: "#EC4899",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-health",
    name: "Kesehatan",
    icon: "HeartPulse",
    emoji: "🏥",
    color: "#22C55E",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-education",
    name: "Pendidikan",
    icon: "BookOpen",
    emoji: "📚",
    color: "#6366F1",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-investment",
    name: "Investasi",
    icon: "TrendingUp",
    emoji: "📈",
    color: "#14B8A6",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-family",
    name: "Anak & Keluarga",
    icon: "Users",
    emoji: "👨‍👩‍👧",
    color: "#F97316",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-donation",
    name: "Hadiah & Donasi",
    icon: "Gift",
    emoji: "🎁",
    color: "#A855F7",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "cat-other",
    name: "Lainnya",
    icon: "Package",
    emoji: "📦",
    color: "#9A9A9F",
    isDefault: true,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
]
